#! /bin/sh
#|
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; This test files tests the students' TCP exploration file.
;; It runs their server and throws JSON at it. 

(provide main)

;; -----------------------------------------------------------------------------
(require SwDev/Testing/harness)

(test-plain-and-pretty-json?             #f)
(test-fast-and-slow-delivery?            #f)
(test-with-and-without-trailing-newline? #f)
(test-with-and-without-escaped-unicode?  #f)

;; Send all inputs first before looking for output
(test-with-batch-mode?                   #t)
; (test-the-first-n-at-most               1)

(unset-time-out #:limit 12)

(define (main tests prog)
 ((client #:tcp #false #:check values) tests prog))
